log_format: console
no_color: false
package:
  oci_concurrency: 15
  create:
    set:
      version: v0.0.0-k3s0
      # renovate: datasource=github-tags depName=k3s-io/k3s versioning=regex:^v(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)\+k3s(?<build>\d+)$
      k3s_version: v1.36.2+k3s1
      k3s_sha_amd: 65a55ec56c24eab44383086166ec620a491952b7e23941a49ddca6e8a4c4b4de
      k3s_sha_arm: 1dc5fc17f15c28fa0a3f011cee28ad613f918c3d967a426e5a05d43ddb239817
      # renovate: datasource=github-tags depName=alexellis/k3sup versioning=regex:^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
      k3sup_version: 0.13.12
      k3sup_sha_amd: 95fe9511cda5ecfa8829a5ce8d3fca6dae68bdd3b0b9946e1634d57761530b45
      k3sup_sha_arm: c6358c9bca8531b424e5484a5f41a710b613ca606d3ab5c724d11c0a39dcce6a
